services:
  # Frontend + Backend App
  app:
    image: ${APP_IMAGE:-ghcr.io/remla25-team14/app:latest}
    build:
      context: ../app
      dockerfile: Dockerfile
      args:
        APP_VERSION: ${APP_VERSION:-development}
    ports:
      - "5001:5001"
    environment:
      - MODEL_SERVICE_URL=http://model-service:5000
      - APP_VERSION=${APP_VERSION:-development}
    depends_on:
      - model-service
    restart: unless-stopped

  # Model Service
  model-service:
    image: ${MODEL_SERVICE_IMAGE:-ghcr.io/remla25-team14/model-service:latest}
    build:
      context: ../model-service
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - OWNER_REPO=${OWNER_REPO:-remla25-team14/model-training}
      - ARTIFACT_ID=${ARTIFACT_ID:-3053668556}
      - PORT=5000
    secrets:
      - github_token
    volumes:
      - model-cache:/app/model_cache
    restart: unless-stopped

volumes:
  model-cache:  

secrets:
  github_token:
    file: ./secrets/github_token.txt  