services:
  # Frontend + Backend App
  app:
    image: ${APP_IMAGE:-ghcr.io/remla25-team14/app:latest}
    build:
      context: ../app
      dockerfile: Dockerfile
      args:
        APP_VERSION: ${APP_VERSION:-development}
    ports:
      - "5001:5001"
    environment:
      - MODEL_SERVICE_URL=http://model-service:5000
      - APP_VERSION=${APP_VERSION:-development}
    depends_on:
      - model-service
    restart: unless-stopped

  # Model Service
  model-service:
    image: ${MODEL_SERVICE_IMAGE:-ghcr.io/remla25-team14/model-service:latest}
    pull_policy: always
    build:
      context: ../model-service
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - MODEL_SERVICE_IMAGE_TAG=${MODEL_SERVICE_IMAGE_TAG:-latest}
      - GITHUB_TOKEN_FILE=/run/secrets/github_token
      - TRAINED_MODEL_VERSION=${TRAINED_MODEL_VERSION:-latest}
      - MODEL_CACHE_DIR=/app/model_cache
    volumes:
      - model-cache:/app/model_cache
    restart: unless-stopped
    secrets:
      - github_token

volumes:
  model-cache:  

secrets:
  github_token:
    file: ./secrets/github_token.txt  