# -*- mode: ruby -*-
# vi: set ft=ruby :

NODE_COUNT = 2
CONTROLLER_IP = "192.168.56.100"
WORKER_IP_START = 101
CTRL_RAM = 4096
CTRL_CPUS = 2
NODE_RAM = 4096 # for testing purposes
NODE_CPUS = 2


Vagrant.configure("2") do |config|
  
  # --- START: Added code to generate inventory file ---
  # This section will create the inventory.cfg file in your project directory.

  inventory_content = <<-INI
# Generated by Vagrantfile on #{Time.now.strftime('%Y-%m-%d %H:%M:%S')}

[controller]
ctrl ansible_host=#{CONTROLLER_IP}

[workers]
  INI

  (1..NODE_COUNT).each do |i|
    worker_name = "node-#{i}"
    worker_ip = "192.168.56.#{WORKER_IP_START + i - 1}"
    inventory_content += "#{worker_name} ansible_host=#{worker_ip}\n"
  end

  inventory_content += <<-INI

[k8s_cluster:children]
controller
workers
  INI

  # Write the content to the file. It will be created/overwritten each time.
  File.write("ansible/inventory.cfg", inventory_content)

  # --- END: Added code to generate inventory file ---


  # Control node configuration
  config.vm.define "ctrl" do |ctrl|
    ctrl.vm.box = "bento/ubuntu-24.04"
    ctrl.vm.hostname = "ctrl"
    ctrl.vm.network "private_network", ip: CONTROLLER_IP
    
    ctrl.vm.provider "virtualbox" do |v|
      v.memory = CTRL_RAM
      v.cpus = CTRL_CPUS
    end

    ctrl.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/general.yaml"
      ansible.inventory_path = "ansible/hosts.ini"
    end
    ctrl.vm.provision "ansible" do |ansible|
     ansible.inventory_path = "ansible/hosts.ini"
     ansible.playbook = "ansible/ctrl.yaml"
    end
  end

  # Worker nodes configuration
  (1..NODE_COUNT).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = "bento/ubuntu-24.04"
      node.vm.hostname = "node-#{i}"
      node.vm.network "private_network", ip: "192.168.56.#{WORKER_IP_START + i - 1}"
      
      node.vm.provider "virtualbox" do |v|
        v.memory = NODE_RAM
        v.cpus = NODE_CPUS
      end

      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/general.yaml"
        ansible.inventory_path = "ansible/hosts.ini"
      end
      node.vm.provision "ansible" do |ansible|
       ansible.inventory_path = "ansible/hosts.ini"
       ansible.playbook = "ansible/node.yaml"
      end
    end
  end
end