{
 "title": "Sentiment Analysis Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate by Sentiment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(sentiment_predictions_total[5m])) by (sentiment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(model_response_time_seconds_sum[5m])\n/\nrate(model_response_time_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Positive Sentiment Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sentiment_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Application Version",
   "type": "stat",
   "description": "Current version of the sentiment-analysis",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API Success Rate by Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(analyze_requests_total{status=\"success\"}[5m])) by (version) / sum(rate(analyze_requests_total[5m])) by (version)",
     "legendFormat": "Version {{version}}"
    }
   ]
  }
 ]
}