apiVersion: v1
kind: Service
metadata:
  name: sentiment-app-service # Service for the user-facing app
  labels:
    app: sentiment-stack # Matches the pod label
spec:
  type: NodePort
  selector:
    app: sentiment-stack # Selects the Pod containing both containers
  ports:
  - protocol: TCP
    port: 5001       # Port this Service will be available on (can be different, e.g. 80)
    targetPort: app-http # Forwards to the named port 'app-http' (containerPort 5001) on the Pod
                      # This specifically targets the sentiment-app-container's port
    name: http