apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentiment-chart.fullname" . }}-model
  labels:
    app: {{ include "sentiment-chart.fullname" . }}-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sentiment-chart.fullname" . }}-model
  template:
    metadata:
      labels:
        app: {{ include "sentiment-chart.fullname" . }}-model
    spec:
      containers:
        - name: sentiment-model
          image: {{ .Values.model.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.githubTokenSecretName }}
                  key: {{ .Values.githubTokenKey }}
            - name: ARTIFACT_ID
              value: "{{ .Values.model.artifactId }}"
            - name: VECT_FILE_NAME_IN_ZIP
              value: "{{ .Values.model.env.VECT_FILE_NAME_IN_ZIP }}"
            - name: MODEL_FILE_NAME_IN_ZIP
              value: "{{ .Values.model.env.MODEL_FILE_NAME_IN_ZIP }}"
            - name: PORT
              value: "{{ .Values.model.port }}"
          ports:
            - containerPort: {{ .Values.model.port }}
          {{- if .Values.sharedVolume.enabled }}
          volumeMounts:
            - name: shared-volume
              mountPath: {{ .Values.sharedVolume.path }}
          {{- end }}
      {{- if .Values.sharedVolume.enabled }}
      volumes:
        - name: shared-volume
          hostPath:
            path: {{ .Values.sharedVolume.hostPath }}
      {{- end }}