{{- if .Values.traffic.abTesting.enabled }}
{{- range $version := .Values.traffic.abTesting.appVersions }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentiment-chart.fullname" $ }}-app-{{ $version }}
  labels:
    app: {{ include "sentiment-chart.fullname" $ }}-app
    version: {{ $version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sentiment-chart.fullname" $ }}-app
      version: {{ $version }}
  template:
    metadata:
      labels:
        app: {{ include "sentiment-chart.fullname" $ }}-app
        version: {{ $version }}
    spec:
      containers:
        - name: sentiment-app
          image: {{ index $.Values.app.images $version }}
          imagePullPolicy: IfNotPresent
          env:
            - name: MODEL_SERVICE_URL
              value: "http://{{ include "sentiment-chart.fullname" $ }}-model:{{ $.Values.model.port }}"
          ports:
            - containerPort: {{ $.Values.app.port }}
          readinessProbe:
            httpGet:
              path: /
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 20
---
{{- end }}
{{- else }}
# Fallback to single version if A/B testing is disabled
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentiment-chart.fullname" . }}-app
  labels:
    app: {{ include "sentiment-chart.fullname" . }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sentiment-chart.fullname" . }}-app
  template:
    metadata:
      labels:
        app: {{ include "sentiment-chart.fullname" . }}-app
    spec:
      containers:
        - name: sentiment-app
          image: {{ .Values.app.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: MODEL_SERVICE_URL
              value: "http://{{ include "sentiment-chart.fullname" . }}-model:{{ .Values.model.port }}"
          ports:
            - containerPort: {{ .Values.app.port }}
          readinessProbe:
            httpGet:
              path: /
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentiment-chart.fullname" . }}-app-v1
  labels:
    app: {{ include "sentiment-chart.fullname" . }}-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sentiment-chart.fullname" . }}-app
      version: v1
  template:
    metadata:
      labels:
        app: {{ include "sentiment-chart.fullname" . }}-app
        version: v1
    spec:
      containers:
        - name: sentiment-app
          image: {{ .Values.app.images.v1 }}
          imagePullPolicy: IfNotPresent
          env:
            - name: MODEL_SERVICE_URL
              value: "http://{{ include "sentiment-chart.fullname" . }}-model-service:{{ .Values.model.port }}"
          ports:
            - containerPort: {{ .Values.app.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentiment-chart.fullname" . }}-app-v2
  labels:
    app: {{ include "sentiment-chart.fullname" . }}-app
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sentiment-chart.fullname" . }}-app
      version: v2
  template:
    metadata:
      labels:
        app: {{ include "sentiment-chart.fullname" . }}-app
        version: v2
    spec:
      containers:
        - name: sentiment-app
          image: {{ .Values.app.images.v2 }}
          imagePullPolicy: IfNotPresent
          env:
            - name: MODEL_SERVICE_URL
              value: "http://{{ include "sentiment-chart.fullname" . }}-model-service:{{ .Values.model.port }}"
          ports:
            - containerPort: {{ .Values.app.port }}
{{- end }}
