apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentiment-chart.fullname" . }}-app
  labels:
    app: {{ include "sentiment-chart.fullname" . }}-app
spec:
  replicas: 1  # Number of pod replicas
  selector:
    matchLabels:
      app: {{ include "sentiment-chart.fullname" . }}-app
  template:
    metadata:
      labels:
        app: {{ include "sentiment-chart.fullname" . }}-app
    spec:
      containers:
        - name: sentiment-app
          image: {{ .Values.app.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.app.port }}
          readinessProbe:
          httpGet:
            path: /
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: MODEL_SERVICE_URL
              value: "http://{{ include "sentiment-chart.fullname" . }}-model:{{ .Values.model.port }}"
            - name: APP_MODE
              valueFrom:
                configMapKeyRef:
                  name: dummy-config
                  key: APP_MODE
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: dummy-config
                  key: LOG_LEVEL