{{- if .Values.traffic.abTesting.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "sentiment-chart.fullname" . }}-app-service
spec:
  host: {{ include "sentiment-chart.fullname" . }}-app-service
  trafficPolicy:
    loadBalancer:
      consistentHash:
        useSourceIp: true
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "sentiment-chart.fullname" . }}-model-destination
spec:
  host: {{ .Values.model.modelurl }}
  subsets:
  {{- range $version := .Values.traffic.abTesting.modelVersions }}
    - name: {{ $version }}
      labels:
        version: {{ $version }}
  {{- end }}
{{- end }}