{{- if and .Values.ingress.enabled (eq .Values.ingress.controller "nginx") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sentiment-chart.fullname" . }}-ingress
  annotations:
    # remove or comment out rewrite-target entirely
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: {{ include "sentiment-chart.fullname" . }}-app-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "sentiment-chart.fullname" . }}-app-service
                port:
                  number: 80
    - host: prometheus.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myprom-kube-prometheus-sta-prometheus
                port:
                  number: 9090
    - host: grafana.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myprom-grafana
                port:
                  number: 80
{{- end }}
