apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentiment-chart.fullname" . }}-model
  labels:
    app: {{ include "sentiment-chart.fullname" . }}-model-serv
spec:
  selector:
    app: {{ include "sentiment-chart.fullname" . }}-model
  ports:
    - port: {{ .Values.model.port }}
      targetPort: {{ .Values.model.port }}
      protocol: TCP
