apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentiment-chart.fullname" . }}-app-service
  labels:
    app: {{ include "sentiment-chart.fullname" . }}-app-serv
spec:
  type: ClusterIP
  selector:
    app: {{ include "sentiment-chart.fullname" . }}-app
  ports:
    - port: {{ .Values.app.servicePort }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
      name: http