apiVersion: v1
kind: Service
metadata:
  name: sentiment-app-service
  labels:
    app: sentiment-stack
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: sentiment-stack