[ctrl]
ctrl ansible_host=192.168.56.100 ansible_user=vagrant

[workers]
node-1 ansible_host=192.168.56.101 ansible_user=vagrant
node-2 ansible_host=192.168.56.102 ansible_user=vagrant

[all:vars]
ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key # If using Vagrant's default key
ansible_user=vagrant