---
- hosts: workers
  become: yes
  tasks:
    - name: Get join command from controller via local vagrant
      ansible.builtin.command: vagrant ssh ctrl -c "sudo kubeadm token create --print-join-command"
      register: kubeadm_join_command_result
      delegate_to: localhost
      become: no  
      run_once: true
      changed_when: false
      
    - name: Debug print join command
      ansible.builtin.debug:
        var: kubeadm_join_command_result.stdout
        
    - name: Join the worker node to the Kubernetes cluster
      ansible.builtin.shell: "{{ kubeadm_join_command_result.stdout }}"
      args:
        creates: /etc/kubernetes/kubelet.conf