---
- name: Join Workers
  hosts: workers
  become: yes
  tasks:

    - name: Get Join Command
      delegate_to: ctrl
      shell: kubeadm token create --print-join-command
      register: join_command
      changed_when: false

    - name: Run Join Command
      shell: "{{ join_command.stdout }}"
      args:
        creates: /etc/kubernetes/kubelet.conf